# Generated by Django 5.0.2 on 2024-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Tester', 'Tester'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
    ]
