# Generated by Django 5.0.2 on 2024-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Tester', 'Tester'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=100, null=True),
        ),
    ]
