# Generated by Django 5.0.2 on 2024-03-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_end_date_project_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Complted', 'Complted'), ('Working', 'Working'), ('Debuging', 'Debuging')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectimg',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
    ]
