# Generated by Django 5.0.2 on 2024-03-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_task_status_alter_project_projectimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='status',
        ),
    ]
