# Generated by Django 5.0.2 on 2024-02-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
