# Generated by Django 5.0.2 on 2024-03-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
    ]
