# Generated by Django 5.0.2 on 2024-03-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_city_user_country_user_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
    ]
