# Generated by Django 5.0.2 on 2024-02-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
