# Generated by Django 5.0.2 on 2024-02-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Complted', 'Complted'), ('Working', 'Working'), ('Debuging', 'Debuging')], max_length=100, null=True),
        ),
    ]
