# Generated by Django 5.0.2 on 2024-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_module_table_task_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectimg',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
    ]
