# Generated by Django 5.0.2 on 2024-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_projectimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectimg',
        ),
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='status',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Complted', 'Complted'), ('Working', 'Working'), ('Debuging', 'Debuging')], max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projectteam',
            table=None,
        ),
    ]
